language: node_js

node_js:
  - "8"

services:
  - docker

install: npm i

cache:
  directories:
    - "node_modules"

script: 
  - npm run lint
  - npm run test:coverage
  - docker build -t registry.heroku.com/hapi-boilerplate-docker/web .
  - docker login --username=_ --password=${HEROKU_TOKEN} registry.heroku.com
  - docker push registry.heroku.com/hapi-boilerplate-docker/web

after_success:
  - cat ./coverage/lcov.info | coveralls