language: node_js

node_js:
  - "8"

services:
  - docker

before_install:
  - docker build -t registry.heroku.com/hapi-boilerplate-docker/web .
  - docker login --username=${HEROKU_LOGIN} --password=${HEROKU_PASSWORD} registry.heroku.com

install: npm i

cache:
  directories:
    - "node_modules"

script: 
  - npm run lint
  - npm run test:coverage
  - docker push registry.heroku.com/hapi-boilerplate-docker/web

after_success:
  - cat ./coverage/lcov.info | coveralls