language: node_js
node_js:
  - "8"
install: npm i
# cache:
#   directories:
#     - "node_modules"
script: 
  - npm run lint
  - npm run test:coverage
after_success:
  - ls -lah ./node_modules
  - cat ./coverage/lcov.info
  - cat ./coverage/lcov.info | coveralls