language: node_js

node_js:
  - "8"

services:
  - docker

env:
  global:
    - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz

before_install:
  - if [ -f ${DOCKER_CACHE_FILE} ]; then gunzip -c ${DOCKER_CACHE_FILE} | docker load; fi

install: npm i

cache:
  directories:
    - "node_modules"
    - "/home/travis/docker/"

script: 
  - npm run lint
  - npm run test:coverage
  - docker build -t registry.heroku.com/hapi-boilerplate-docker/web .
  - docker login --username=_ --password=${HEROKU_TOKEN} registry.heroku.com
  - docker push registry.heroku.com/hapi-boilerplate-docker/web
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then mkdir -p $(dirname ${DOCKER_CACHE_FILE}) ; docker save $(docker history -q ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} | grep -v '<missing>') | gzip > ${DOCKER_CACHE_FILE}; fi

after_success:
  - cat ./coverage/lcov.info | coveralls