language: node_js

node_js:
  - "8"

services:
  - docker

env:
  global:
    - DOCKER_REPOSITORY=registry.heroku.com
    - DOCKER_DEPLOY_PATH=${DOCKER_REPOSITORY}/${TRAVIS_REPO_SLUG#*/}

install: npm i

cache:
  directories:
    - "node_modules"

script: 
  - npm run lint
  - npm run test:coverage
  - docker build --cache-from node:8.9.1-alpine -t ${DOCKER_DEPLOY_PATH}/web .
  - docker login --username=_ --password=${HEROKU_TOKEN} ${DOCKER_REPOSITORY}
  - docker push ${DOCKER_DEPLOY_PATH}/web

after_success:
  - cat ./coverage/lcov.info | coveralls