version: '3'
services:
  boilerplate:
    build: .
    container_name: hapi-boilerplate
    ports:
      - '3000:3000'
    volumes:
      - ./src/:/usr/app/src/
      - ./ssl/:/usr/app/ssl/:ro
    env_file:
      - .env
