#!/bin/sh

echo "pre-commit hook"

echo "running -> Tests"
# Run tests
npm test

echo "running -> Linting"
# Run tests
npm test

echo "running -> Prettier"
# Run prettier before committing
npm run pretty
